import { build } from 'esbuild';
import { copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../', import.meta.url));
await build({
  absWorkingDir: root,
  entryPoints: ['coffee-terminal/web/robot/app.mjs'],
  outfile: 'coffee-terminal/web/robot-scene.bundle.js',
  bundle: true, minify: true, format: 'iife', target: ['es2020'], legalComments: 'eof',
  banner: { js: '/* Generated by npm run build:scene. Source: web/robot/. Includes Three.js (MIT). */' },
});
await copyFile(new URL('../node_modules/three/LICENSE', import.meta.url), new URL('../coffee-terminal/web/robot/THREE-LICENSE.txt', import.meta.url));
for (const [entry,name] of [['live-viewer','robot-live'],['integration','robot-integration']]) {
  await build({absWorkingDir:root,entryPoints:[`coffee-terminal/web/robot/${entry}.mjs`],
    outfile:`coffee-terminal/web/${name}.bundle.js`,bundle:true,minify:true,format:'iife',target:['es2020'],legalComments:'eof'});
}
console.log('Built offline-ready Three.js scene.');
