// Optional real-browser regression suite. Requires Playwright; does not mutate the device service.
import {build} from 'esbuild';
import {writeFile,mkdir,mkdtemp} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
const option=(name,fallback)=>{const i=process.argv.indexOf(name);return i<0?fallback:process.argv[i+1];};
const base=option('--url','http://127.0.0.1:9133'),out=option('--output',await mkdtemp(join(tmpdir(),'coffee-studio-qa-')));
await mkdir(out,{recursive:true});
const root=fileURLToPath(new URL('../',import.meta.url));
// Test-only introspection wraps the real Renderer and loads the real app. No fake worker/state.
const compiled=await build({stdin:{contents:`import {TwinRenderer} from './coffee-terminal/web/twin/renderer.mjs';import * as THREE from 'three';
window.qa={renderers:[],THREE};const bind=TwinRenderer.prototype.bindPicking;TwinRenderer.prototype.bindPicking=function(){window.qa.renderers.push(this);return bind.call(this);};
await import('./coffee-terminal/web/twin/app.mjs');`,resolveDir:root,sourcefile:'qa.mjs'},bundle:true,format:'esm',target:'es2022',loader:{'.svg':'text'},write:false});
const harness=compiled.outputFiles[0].text;
const browser=await chromium.launch({headless:true,channel:'chromium'}),page=await browser.newPage({viewport:{width:1440,height:900},acceptDownloads:true}),errors=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.addInitScript(()=>{
 const added=EventTarget.prototype.addEventListener,removed=EventTarget.prototype.removeEventListener;window.canvasListeners=new Map();
 EventTarget.prototype.addEventListener=function(type,fn,options){if(this instanceof HTMLCanvasElement){let m=canvasListeners.get(this);if(!m)canvasListeners.set(this,m=new Map());if(!m.has(type))m.set(type,new Set());m.get(type).add(fn);}return added.call(this,type,fn,options);};
 EventTarget.prototype.removeEventListener=function(type,fn,options){if(this instanceof HTMLCanvasElement)canvasListeners.get(this)?.get(type)?.delete(fn);return removed.call(this,type,fn,options);};
});
await page.route('**/digital-twin.bundle.js',r=>r.fulfill({contentType:'application/javascript',body:harness}));
const ready=()=>page.waitForFunction(()=>qa.renderers.at(-1)?.state&&!document.querySelector('#play').disabled);
const ref=()=>page.evaluate(()=>qa.renderers.at(-1).selectedRef);
const camera=()=>page.evaluate(()=>{const r=qa.renderers.at(-1);return [...r.camera.position.toArray(),...r.controls.target.toArray()];});
const tree=async(kind,id)=>{await page.locator(`[data-selection-key="${kind}:${id}"]`).click();};
const findPoint=async(kind,id)=>page.evaluate(({kind,id})=>{
 const r=qa.renderers.at(-1),T=qa.THREE,root=r.entityRoots.get(`${kind}:${id}`);r.scene.updateMatrixWorld(true);r.camera.updateMatrixWorld();const rect=r.renderer.domElement.getBoundingClientRect(),points=[];
 root.traverse(n=>{if(n.isMesh){const box=new T.Box3().setFromObject(n);points.push(box.getCenter(new T.Vector3()));for(const x of [.25,.75])for(const y of [.25,.75])for(const z of [.25,.75])points.push(new T.Vector3().copy(box.min).lerp(box.max,.5).set(box.min.x+(box.max.x-box.min.x)*x,box.min.y+(box.max.y-box.min.y)*y,box.min.z+(box.max.z-box.min.z)*z));}});
 for(const p of points){const v=p.project(r.camera),x=rect.x+(v.x+1)/2*rect.width,y=rect.y+(1-v.y)/2*rect.height;if(x<rect.x+10||x>rect.right-10||y<rect.y+100||y>rect.bottom-25)continue;const hit=r.pick({clientX:x,clientY:y});if(hit?.kind===kind&&hit.id===id)return {x,y};}
 return null;
},{kind,id});
try{
 await page.goto(base+'/digital-twin.html?source=device-lab');await page.waitForFunction(()=>document.querySelector('#config-feedback').textContent.includes('已载入设备'));await ready();await page.locator('[data-panel="scene"]').click();await page.locator('#view').selectOption('workcell');
 await tree('device','brewer');assert.deepEqual(await ref(),{kind:'device',id:'brewer'});assert.ok(await page.locator('[data-task-id="extract"]').evaluate(e=>e.classList.contains('task-related')));assert.match(await page.locator('#inspector-content').textContent(),/28.000 s/);assert.equal(await page.evaluate(()=>qa.renderers.at(-1).selectionHelper.material.color.getHexString()),'b78a52');checks.push('A tree brewer -> inspector/timeline/brass');
 await page.locator('[data-task-id="extract"]').click();assert.deepEqual(await ref(),{kind:'task',id:'extract'});assert.ok(await page.locator('[data-selection-key="device:brewer"]').evaluate(e=>e.classList.contains('related')));assert.equal(await page.evaluate(()=>qa.renderers.at(-1).selectionHelper),null);checks.push('C task extract -> related entities, no false selected device');
 await tree('robot','left');await page.keyboard.press('f');await page.waitForTimeout(250);let point=await findPoint('robot','left');assert.ok(point,'robot pick point');await page.keyboard.press('Escape');await page.mouse.click(point.x,point.y);assert.deepEqual(await ref(),{kind:'robot',id:'left'});checks.push('B actual raycast left robot');
 const beforeDrag=await ref();const box=await page.locator('#viewport canvas').boundingBox();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.6);await page.mouse.down();await page.mouse.move(box.x+box.width*.6+70,box.y+box.height*.6+20,{steps:8});await page.mouse.move(box.x+box.width*.6,box.y+box.height*.6,{steps:8});await page.mouse.up();assert.deepEqual(await ref(),beforeDrag);checks.push('D orbit out-and-back does not select');
 await page.locator('#view').selectOption('workcell');await tree('device','brewer');await page.keyboard.press('f');await page.waitForTimeout(250);point=await findPoint('device','brewer');assert.ok(point);await page.locator('#view').selectOption('workcell');point=await findPoint('device','brewer');assert.ok(point);const beforeDouble=await camera();await page.mouse.dblclick(point.x,point.y);await page.waitForTimeout(250);assert.deepEqual(await ref(),{kind:'device',id:'brewer'});assert.notDeepEqual(await camera(),beforeDouble);checks.push('E double click focus');
 await tree('gripper','left-gripper');const beforeFocus=await camera();await page.keyboard.press('f');await page.waitForTimeout(250);assert.notDeepEqual(await camera(),beforeFocus);point=await findPoint('gripper','left-gripper');assert.ok(point,'gripper pick point');await page.keyboard.press('Escape');await page.mouse.click(point.x,point.y);assert.deepEqual(await ref(),{kind:'gripper',id:'left-gripper'});assert.match(await page.locator('#inspector-content').textContent(),/Target120.000 mm/);checks.push('nested gripper takes priority; real target aperture');
 await page.keyboard.press('Escape');assert.equal(await ref(),null);assert.equal(await page.locator('.tree-row.selected,.tree-row.related,.task-selected,.task-related').count(),0);checks.push('F/G focus and clear');
 await page.locator('#view').selectOption('top');point=await findPoint('station','handoff');assert.ok(point,'station visible pad is pickable');await page.mouse.click(point.x,point.y);assert.deepEqual(await ref(),{kind:'station',id:'handoff'});checks.push('station pad picks station');
 // Helper resources are disposed, not accumulated, under rapid cross-selection.
 await page.evaluate(()=>{window.disposedHelpers=0;const r=qa.renderers.at(-1),original=r.addSelectionHelper;r.addSelectionHelper=function(...args){const h=original.apply(this,args);if(h)h.geometry.addEventListener('dispose',()=>disposedHelpers++);return h;};});
 const memory=await page.evaluate(()=>qa.renderers.at(-1).renderer.info.memory.geometries);
 for(let i=0;i<30;i++)await tree('device',i%2?'brewer':'foamer');await page.keyboard.press('Escape');await page.waitForTimeout(150);const resources=await page.evaluate(()=>({disposed:disposedHelpers,geometries:qa.renderers.at(-1).renderer.info.memory.geometries}));assert.ok(resources.disposed>=58);assert.ok(resources.geometries<=memory+2);checks.push('30 selections release helper geometries');
 await page.locator('#view').selectOption('workcell');await tree('device','brewer');await page.keyboard.press('f');await page.waitForTimeout(200);const cam=await camera();await page.locator('#inspector-toggle').click();await page.waitForTimeout(200);assert.ok((await camera()).every((v,i)=>Math.abs(v-cam[i])<1e-4),'resize preserves camera within damping tolerance');await page.locator('#inspector-toggle').click();await page.locator('#dock-collapse').click();await page.waitForTimeout(200);assert.ok((await camera()).every((v,i)=>Math.abs(v-cam[i])<1e-4),'resize preserves camera within damping tolerance');await page.locator('#dock-collapse').click();
 const grip=await page.locator('#dock-grip').boundingBox();await page.mouse.move(grip.x+100,grip.y+3);await page.mouse.down();await page.mouse.move(grip.x+100,grip.y-65,{steps:6});await page.mouse.up();await page.waitForTimeout(150);assert.ok((await camera()).every((v,i)=>Math.abs(v-cam[i])<1e-4),'resize preserves camera within damping tolerance');assert.ok(await page.evaluate(()=>{const r=qa.renderers.at(-1);return Math.abs(r.camera.aspect-r.host.clientWidth/r.host.clientHeight)<1e-8;}));checks.push('panel collapse / dock resize resizes canvas without camera jump');
 await page.locator('#inspector-close').click();await page.locator('#side-close').click();await page.reload();await ready();assert.ok(await page.locator('#inspector').evaluate(e=>e.classList.contains('hidden')));assert.ok(await page.locator('#side-panel').evaluate(e=>e.classList.contains('hidden')));await page.locator('#inspector-toggle').click();await page.locator('[data-panel="scene"]').click();checks.push('layout visibility persisted through reload');
 await tree('device','foamer');await page.evaluate(()=>{window.inspectorButton=document.querySelector('[data-context-focus]');window.taskRow=document.querySelector('[data-task-id="foam"]');});await page.locator('#speed').selectOption('16');await page.locator('#play').click();await page.waitForFunction(()=>qa.renderers.at(-1).state.tasks.foam.status==='running');await page.locator('#play').click();await page.waitForTimeout(150);assert.ok(await page.evaluate(()=>inspectorButton===document.querySelector('[data-context-focus]')&&taskRow===document.querySelector('[data-task-id="foam"]')));assert.match(await page.locator('[data-selection-key="device:foamer"] [data-tree-status]').textContent(),/running/);assert.match(await page.locator('#inspector-content').textContent(),/running/);assert.ok(await page.locator('[data-task-id="foam"]').evaluate(e=>e.classList.contains('running')&&e.classList.contains('task-related')));checks.push('H live tree / inspector / timeline consistency and stable interactive DOM');
 for(let i=0;i<3;i++){await page.locator('#reset').click();await ready();assert.deepEqual(await ref(),{kind:'device',id:'foamer'});assert.equal(await page.locator('#viewport canvas').count(),1);}
 const lifecycle=await page.evaluate(()=>qa.renderers.slice(0,-1).map(r=>({disposed:r.disposed,helper:r.selectionHelper,related:r.relatedHelpers.length,pointerListeners:[...(canvasListeners.get(r.renderer.domElement)??new Map())].filter(([k])=>k.startsWith('pointer')).reduce((sum,[,s])=>sum+s.size,0)})));for(const r of lifecycle){assert.equal(r.disposed,true);assert.equal(r.helper,null);assert.equal(r.related,0);assert.equal(r.pointerListeners,0);}checks.push('I reset 3x preserves stable selection, one canvas, zero old pointer listeners');
 // Advance/Export/Replay then repeat reconstruction, preserving the selected task.
 await page.locator('#step').click();await page.waitForFunction(()=>qa.renderers.at(-1).state.tick>0);await page.locator('[data-task-id="extract"]').click();await page.locator('[data-panel="experiment"]').click();const dl=page.waitForEvent('download');await page.locator('#export').click();await(await dl).saveAs(join(out,'replay.json'));
 for(let i=0;i<3;i++){await page.locator('#replay-file').setInputFiles(join(out,'replay.json'));await page.waitForFunction(()=>!document.querySelector('#seek').disabled);await page.waitForTimeout(100);assert.deepEqual(await ref(),{kind:'task',id:'extract'});assert.equal(await page.locator('#viewport canvas').count(),1);await page.locator('#replay-file').evaluate(e=>e.value='');}
 checks.push('I replay 3x, stable task selection and one canvas');
 await page.locator('#reset').click();await ready();await page.locator('[data-panel="scene"]').click();await page.locator('#view').selectOption('workcell');await tree('device','brewer');await page.screenshot({path:join(out,'studio-desktop.png')});
 assert.deepEqual(errors,[]);const report={checks,resources,lifecycle,errors};await writeFile(join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({...report,output:out},null,2));
}catch(e){await page.screenshot({path:join(out,'failed.png')}).catch(()=>{});console.log(JSON.stringify({checks,errors,error:e.stack},null,2));process.exitCode=1;}finally{await browser.close();}
